// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cOGSSLB
SEXP cOGSSLB(SEXP dis_SEXP, SEXP Y_SEXP, SEXP B_init, SEXP sigmas_init, SEXP Tau_init, SEXP thetas_init, SEXP theta_tildes_init, SEXP nus_init, SEXP lambda1_SEXP, SEXP lambda0s_SEXP, SEXP lambda1_tilde_SEXP, SEXP lambda0_tildes_SEXP, SEXP weights_SEXP, SEXP a_SEXP, SEXP b_SEXP, SEXP a_tilde_SEXP, SEXP b_tilde_SEXP, SEXP alpha_SEXP, SEXP d_SEXP, SEXP eta_SEXP, SEXP xi_SEXP, SEXP sigma_min_SEXP, SEXP IBP_SEXP, SEXP EPSILON_SEXP, SEXP MAX_ITER_SEXP, SEXP plot_conv_SEXP, SEXP iter_em_to_plot_SEXP, SEXP dir_save_weight_grad_SEXP, SEXP l2_reg_log_reg_SEXP, SEXP stepsize_graddesc_logreg_SEXP, SEXP niter_burnIn_ULA_SOUL_SEXP, SEXP niter_ULA_SOUL_SEXP, SEXP niter_graddesc_logreg_SEXP, SEXP niter_expgrad_graddesc_logreg_SEXP, SEXP niter_exp_y_SEXP, SEXP manual_set_stepsize_hyperparam_logreg_SEXP, SEXP perc_max_stepsize_grad_desc_SEXP);
RcppExport SEXP _OGSSLB_cOGSSLB(SEXP dis_SEXPSEXP, SEXP Y_SEXPSEXP, SEXP B_initSEXP, SEXP sigmas_initSEXP, SEXP Tau_initSEXP, SEXP thetas_initSEXP, SEXP theta_tildes_initSEXP, SEXP nus_initSEXP, SEXP lambda1_SEXPSEXP, SEXP lambda0s_SEXPSEXP, SEXP lambda1_tilde_SEXPSEXP, SEXP lambda0_tildes_SEXPSEXP, SEXP weights_SEXPSEXP, SEXP a_SEXPSEXP, SEXP b_SEXPSEXP, SEXP a_tilde_SEXPSEXP, SEXP b_tilde_SEXPSEXP, SEXP alpha_SEXPSEXP, SEXP d_SEXPSEXP, SEXP eta_SEXPSEXP, SEXP xi_SEXPSEXP, SEXP sigma_min_SEXPSEXP, SEXP IBP_SEXPSEXP, SEXP EPSILON_SEXPSEXP, SEXP MAX_ITER_SEXPSEXP, SEXP plot_conv_SEXPSEXP, SEXP iter_em_to_plot_SEXPSEXP, SEXP dir_save_weight_grad_SEXPSEXP, SEXP l2_reg_log_reg_SEXPSEXP, SEXP stepsize_graddesc_logreg_SEXPSEXP, SEXP niter_burnIn_ULA_SOUL_SEXPSEXP, SEXP niter_ULA_SOUL_SEXPSEXP, SEXP niter_graddesc_logreg_SEXPSEXP, SEXP niter_expgrad_graddesc_logreg_SEXPSEXP, SEXP niter_exp_y_SEXPSEXP, SEXP manual_set_stepsize_hyperparam_logreg_SEXPSEXP, SEXP perc_max_stepsize_grad_desc_SEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dis_SEXP(dis_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Y_SEXP(Y_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type B_init(B_initSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sigmas_init(sigmas_initSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Tau_init(Tau_initSEXP);
    Rcpp::traits::input_parameter< SEXP >::type thetas_init(thetas_initSEXP);
    Rcpp::traits::input_parameter< SEXP >::type theta_tildes_init(theta_tildes_initSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nus_init(nus_initSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambda1_SEXP(lambda1_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambda0s_SEXP(lambda0s_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambda1_tilde_SEXP(lambda1_tilde_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambda0_tildes_SEXP(lambda0_tildes_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type weights_SEXP(weights_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type a_SEXP(a_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b_SEXP(b_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type a_tilde_SEXP(a_tilde_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type b_tilde_SEXP(b_tilde_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type alpha_SEXP(alpha_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type d_SEXP(d_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type eta_SEXP(eta_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xi_SEXP(xi_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type sigma_min_SEXP(sigma_min_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type IBP_SEXP(IBP_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type EPSILON_SEXP(EPSILON_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type MAX_ITER_SEXP(MAX_ITER_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type plot_conv_SEXP(plot_conv_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type iter_em_to_plot_SEXP(iter_em_to_plot_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dir_save_weight_grad_SEXP(dir_save_weight_grad_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type l2_reg_log_reg_SEXP(l2_reg_log_reg_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type stepsize_graddesc_logreg_SEXP(stepsize_graddesc_logreg_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type niter_burnIn_ULA_SOUL_SEXP(niter_burnIn_ULA_SOUL_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type niter_ULA_SOUL_SEXP(niter_ULA_SOUL_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type niter_graddesc_logreg_SEXP(niter_graddesc_logreg_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type niter_expgrad_graddesc_logreg_SEXP(niter_expgrad_graddesc_logreg_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type niter_exp_y_SEXP(niter_exp_y_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type manual_set_stepsize_hyperparam_logreg_SEXP(manual_set_stepsize_hyperparam_logreg_SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type perc_max_stepsize_grad_desc_SEXP(perc_max_stepsize_grad_desc_SEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(cOGSSLB(dis_SEXP, Y_SEXP, B_init, sigmas_init, Tau_init, thetas_init, theta_tildes_init, nus_init, lambda1_SEXP, lambda0s_SEXP, lambda1_tilde_SEXP, lambda0_tildes_SEXP, weights_SEXP, a_SEXP, b_SEXP, a_tilde_SEXP, b_tilde_SEXP, alpha_SEXP, d_SEXP, eta_SEXP, xi_SEXP, sigma_min_SEXP, IBP_SEXP, EPSILON_SEXP, MAX_ITER_SEXP, plot_conv_SEXP, iter_em_to_plot_SEXP, dir_save_weight_grad_SEXP, l2_reg_log_reg_SEXP, stepsize_graddesc_logreg_SEXP, niter_burnIn_ULA_SOUL_SEXP, niter_ULA_SOUL_SEXP, niter_graddesc_logreg_SEXP, niter_expgrad_graddesc_logreg_SEXP, niter_exp_y_SEXP, manual_set_stepsize_hyperparam_logreg_SEXP, perc_max_stepsize_grad_desc_SEXP));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_OGSSLB_cOGSSLB", (DL_FUNC) &_OGSSLB_cOGSSLB, 37},
    {NULL, NULL, 0}
};

RcppExport void R_init_OGSSLB(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
